"""empty message

Revision ID: 7a076e420f02
Revises: 31e3b39c211f
Create Date: 2017-05-28 09:44:32.245119

"""

# revision identifiers, used by Alembic.
revision = '7a076e420f02'
down_revision = '31e3b39c211f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('market_orders', 'price', existing_type=sa.Integer(), type_=sa.BigInteger())
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('market_orders', 'price', existing_type=sa.BigInteger(), type_=sa.Integer())
    # ### end Alembic commands ###
